export const sampleInternships = [
  {
    id: 1,
    title: "Software Development Intern",
    company: "TechCorp Solutions",
    location: "Bangalore, Karnataka",
    duration: "3 months",
    stipend: "₹15,000 - ₹25,000",
    workMode: "Remote",
    type: "Full-time",
    datePosted: "2024-01-15",
    deadline: "2024-02-15",
    shortDescription: "Work on real-world projects using React, Node.js, and MongoDB",
    description: "Join our dynamic team as a Software Development Intern and gain hands-on experience in full-stack development. You'll work on cutting-edge projects using modern technologies like React, Node.js, and MongoDB.",
    requirements: ["Currently pursuing Computer Science or related field", "Basic knowledge of JavaScript", "Familiarity with React or Node.js", "Strong problem-solving skills"],
    skills: ["JavaScript", "React", "Node.js", "MongoDB", "Git"],
    benefits: ["Certificate of completion", "Mentorship program", "Flexible working hours", "Potential for full-time offer"]
  },
  {
    id: 2,
    title: "Digital Marketing Intern",
    company: "Creative Agency",
    location: "Mumbai, Maharashtra",
    duration: "6 months",
    stipend: "₹12,000 - ₹18,000",
    workMode: "Hybrid",
    type: "Part-time",
    datePosted: "2024-01-14",
    deadline: "2024-02-20",
    shortDescription: "Learn digital marketing strategies, SEO, and social media management",
    description: "Gain practical experience in digital marketing by working with real clients. Learn SEO, social media marketing, content creation, and analytics.",
    requirements: ["Marketing or Business student", "Basic understanding of social media", "Creative mindset", "Good communication skills"],
    skills: ["SEO", "Social Media Marketing", "Content Creation", "Google Analytics", "Canva"],
    benefits: ["Industry exposure", "Portfolio development", "Networking opportunities", "Performance-based incentives"]
  },
  {
    id: 3,
    title: "Data Science Intern",
    company: "Analytics Pro",
    location: "Hyderabad, Telangana",
    duration: "4 months",
    stipend: "₹20,000 - ₹30,000",
    workMode: "On-site",
    type: "Full-time",
    datePosted: "2024-01-13",
    deadline: "2024-02-10",
    shortDescription: "Work with big data, machine learning models, and data visualization",
    description: "Join our data science team to work on machine learning projects, data analysis, and visualization. Perfect opportunity to apply theoretical knowledge in real-world scenarios.",
    requirements: ["Statistics or Computer Science background", "Python programming skills", "Knowledge of pandas, numpy", "Understanding of ML concepts"],
    skills: ["Python", "Machine Learning", "Data Analysis", "SQL", "Tableau"],
    benefits: ["Real project experience", "Industry mentorship", "Skill development workshops", "Letter of recommendation"]
  },
  {
    id: 4,
    title: "UI/UX Design Intern",
    company: "Design Studio",
    location: "Pune, Maharashtra",
    duration: "3 months",
    stipend: "₹10,000 - ₹20,000",
    workMode: "Remote",
    type: "Part-time",
    datePosted: "2024-01-12",
    deadline: "2024-02-25",
    shortDescription: "Create user interfaces and improve user experience for web and mobile apps",
    description: "Work alongside experienced designers to create intuitive user interfaces and enhance user experiences for various digital products.",
    requirements: ["Design or related field student", "Basic knowledge of design principles", "Familiarity with design tools", "Creative portfolio"],
    skills: ["Figma", "Adobe XD", "Photoshop", "User Research", "Prototyping"],
    benefits: ["Portfolio enhancement", "Design mentorship", "Client interaction", "Flexible schedule"]
  },
  {
    id: 5,
    title: "Content Writing Intern",
    company: "Media House",
    location: "Delhi, Delhi",
    duration: "2 months",
    stipend: "₹8,000 - ₹15,000",
    workMode: "Hybrid",
    type: "Part-time",
    datePosted: "2024-01-11",
    deadline: "2024-03-01",
    shortDescription: "Create engaging content for blogs, social media, and marketing campaigns",
    description: "Join our content team to create compelling articles, blog posts, and marketing content. Learn content strategy and SEO writing techniques.",
    requirements: ["English or Journalism student", "Excellent writing skills", "Research abilities", "Basic SEO knowledge"],
    skills: ["Content Writing", "SEO Writing", "Research", "WordPress", "Social Media"],
    benefits: ["Published work portfolio", "Writing skill development", "Industry connections", "Byline opportunities"]
  }
];