export const sampleWebinars = [
  {
    id: 1,
    title: "AI & Machine Learning in 2024",
    speaker: "Dr. Sarah Johnson",
    organization: "Tech Institute",
    date: "2024-02-15",
    time: "10:00 AM - 12:00 PM",
    mode: "Online",
    platform: "Zoom",
    price: "Free",
    category: "Technology",
    shortDescription: "Explore the latest trends in AI and ML technologies",
    description: "Join us for an in-depth exploration of artificial intelligence and machine learning trends that are shaping 2024. Learn about breakthrough technologies, practical applications, and future opportunities in this rapidly evolving field.",
    agenda: ["Introduction to AI/ML trends", "Real-world applications", "Future predictions", "Q&A session"],
    requirements: ["Basic understanding of technology", "Laptop/mobile device", "Stable internet connection"],
    benefits: ["Certificate of participation", "Networking opportunities", "Resource materials", "Recording access"]
  },
  {
    id: 2,
    title: "Digital Marketing Masterclass",
    speaker: "Mark Thompson",
    organization: "Marketing Pro",
    date: "2024-02-20",
    time: "2:00 PM - 5:00 PM",
    mode: "Offline",
    venue: "Business Center, Mumbai",
    price: "₹999",
    category: "Marketing",
    shortDescription: "Master digital marketing strategies and tools",
    description: "A comprehensive masterclass covering all aspects of digital marketing including SEO, social media marketing, content strategy, and analytics. Perfect for beginners and intermediate marketers.",
    agenda: ["SEO fundamentals", "Social media strategies", "Content marketing", "Analytics and measurement"],
    requirements: ["Marketing background preferred", "Notebook for taking notes", "Business cards for networking"],
    benefits: ["Hands-on workshop", "Industry insights", "Networking lunch", "Course materials"]
  },
  {
    id: 3,
    title: "Startup Funding & Investment",
    speaker: "Priya Sharma",
    organization: "Venture Capital Hub",
    date: "2024-02-25",
    time: "6:00 PM - 8:00 PM",
    mode: "Online",
    platform: "Google Meet",
    price: "₹499",
    category: "Business",
    shortDescription: "Learn how to secure funding for your startup",
    description: "Understand the startup funding landscape, from seed funding to Series A and beyond. Learn how to pitch to investors, prepare financial projections, and navigate the investment process.",
    agenda: ["Funding stages explained", "Pitch deck essentials", "Investor relations", "Legal considerations"],
    requirements: ["Startup idea or business", "Basic business knowledge", "Pitch deck (optional)"],
    benefits: ["Investor contact list", "Pitch deck template", "1-on-1 consultation", "Community access"]
  },
  {
    id: 4,
    title: "Web Development Bootcamp",
    speaker: "Alex Rodriguez",
    organization: "Code Academy",
    date: "2024-03-01",
    time: "9:00 AM - 6:00 PM",
    mode: "Offline",
    venue: "Tech Hub, Bangalore",
    price: "₹1999",
    category: "Technology",
    shortDescription: "Full-day intensive web development workshop",
    description: "An intensive full-day bootcamp covering HTML, CSS, JavaScript, and React. Build real projects and get hands-on experience with modern web development tools and frameworks.",
    agenda: ["HTML/CSS basics", "JavaScript fundamentals", "React introduction", "Project building"],
    requirements: ["Laptop with code editor", "Basic computer skills", "Enthusiasm to learn"],
    benefits: ["Project portfolio", "Code repository access", "Mentorship program", "Job placement assistance"]
  },
  {
    id: 5,
    title: "Personal Finance & Investment",
    speaker: "Rajesh Kumar",
    organization: "Finance Experts",
    date: "2024-03-05",
    time: "7:00 PM - 9:00 PM",
    mode: "Online",
    platform: "Teams",
    price: "Free",
    category: "Finance",
    shortDescription: "Smart strategies for personal wealth building",
    description: "Learn essential personal finance management skills including budgeting, saving, investing in stocks and mutual funds, and planning for retirement. Suitable for all age groups.",
    agenda: ["Budgeting basics", "Investment options", "Risk management", "Retirement planning"],
    requirements: ["Basic math skills", "Interest in financial planning", "Calculator or smartphone"],
    benefits: ["Financial planning template", "Investment calculator", "Expert consultation", "Resource library"]
  }
];